In [12]:
import numpy as np

In [13]:
# Augmented matrix [A | b]

matrix = np.array([
    [ 2,  3, -1,  5],
    [-1,  7,  2,  3],
    [ 4, -5,  1, -2]
], dtype=float)

n = len(matrix)

In [14]:
print("Original matrix:")
print(matrix)

Original matrix:
[[ 2.  3. -1.  5.]
 [-1.  7.  2.  3.]
 [ 4. -5.  1. -2.]]


In [15]:
# Forward Elimination

for i in range(n):
    # Make the diagonal element 1
    matrix[i] = matrix[i] / matrix[i][i]
    for j in range(i+1, n):
        matrix[j] = matrix[j] - matrix[j][i] * matrix[i]


In [16]:
print("Matrix after forward elimination:")
print(matrix)

Matrix after forward elimination:
[[ 1.          1.5        -0.5         2.5       ]
 [ 0.          1.          0.17647059  0.64705882]
 [ 0.          0.          1.         -0.98809524]]


In [17]:
# Back Substitution

x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = matrix[i][-1] - sum(matrix[i][j] * x[j] for j in range(i+1, n))

In [18]:
# Print results
variables = ['x', 'y', 'z']
for var, val in zip(variables, x):
    print(f"{var} = {val:.2f}")

x = 0.77
y = 0.82
z = -0.99
